version: '3'

services:
  
  db:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "orion123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
        - ./database:/var/opt/mssql/data
    healthcheck:
      test: sqlcmd -S db1.internal.dev.nuarca.com -U SA -P 'Alaska2017' -Q 'SELECT GETDATE()'
    networks:
      mynetwork:
        aliases:
          - db1.internal.dev.nuarca.com

networks:
  mynetwork:
    driver: bridge