version: "3.7"

services:

  mssql:
    user: root
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "orion123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
        - ./data:/var/opt/mssql/data
        - ./scripts:/home/scripts

volumes:
  data:
  scripts:
