version: '3.9'

services:
  
  mssql:
    user: root
    build:
      context: ./docker/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "orion123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
        - ./database:/var/opt/mssql/data
        - ./deployment:/home/deployment

